### ISSUE TITLE
Add nx action

### ISSUE THREAD

**Issue by jannikwienecke** [jannikwienecke/web-dev#9]
## Summary

- Add nx action
- 
### Basic example

```
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
      - 
```

### Motivation

- if the developer skips the pre-commit, we want ensure that all linting, tests and type checks still run before we merge the pull request
